/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Cbas
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        EstereoPicnicBg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        Bg.setBackground(new java.awt.Color(255, 255, 255));
        Bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/imagen_1.png"))); // NOI18N
        Bg.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 90));

        EstereoPicnicBg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EstereoPicnicBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Imagenes/imagen_2.jpg"))); // NOI18N
        Bg.add(EstereoPicnicBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 500));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREVENTA VIP");
        Bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 510, -1));

        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Bizarrap", "Armin Van Buuren", "Moderat" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        Bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 450, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS DEL COMPRADOR");
        Bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 510, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("N° de Boletas:");
        Bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 180, -1));
        Bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 510, 10));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Función:");
        Bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Cedula:");
        Bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 180, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("Nombre Completo:");
        Bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 180, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Correo Electrónico:");
        Bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 180, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("Teléfono:");
        Bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 180, -1));

        jTextField2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Bg.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 250, -1));

        jTextField3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Bg.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 250, -1));

        jTextField4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Bg.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 250, -1));

        jTextField5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Bg.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 250, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 255));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Terminar Preventa");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, 40));

        jSpinner1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jSpinner1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Bg.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel EstereoPicnicBg;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
